;----------------------------------------------------------------------------
; 在下列类型值命名中：
;       DA_  : Descriptor Attribute
;       D    : 数据段
;       C    : 代码段
;       S    : 系统段
;       R    : 只读
;       RW   : 读写
;       A    : 已访问
;       其它 : 可按照字面意思理解
;----------------------------------------------------------------------------

; 描述符类型
DA_32		EQU	4000h	; 32 位段

DA_DPL0		EQU	  00h	; DPL = 0
DA_DPL1		EQU	  20h	; DPL = 1
DA_DPL2		EQU	  40h	; DPL = 2
DA_DPL3		EQU	  60h	; DPL = 3

; 存储段描述符类型
DA_DR		EQU	90h	; 存在的只读数据段类型值
DA_DRW		EQU	92h	; 存在的可读写数据段属性值
DA_DRWA		EQU	93h	; 存在的已访问可读写数据段类型值
DA_C		EQU	98h	; 存在的只执行代码段属性值
DA_CR		EQU	9Ah	; 存在的可执行可读代码段属性值
DA_CCO		EQU	9Ch	; 存在的只执行一致代码段属性值
DA_CCOR		EQU	9Eh	; 存在的可执行可读一致代码段属性值

; 系统段描述符类型
DA_LDT		EQU	  82h	; 局部描述符表段类型值
DA_TaskGate	EQU	  85h	; 任务门类型值
DA_386TSS	EQU	  89h	; 可用 386 任务状态段类型值
DA_386CGate	EQU	  8Ch	; 386 调用门类型值
DA_386IGate	EQU	  8Eh	; 386 中断门类型值
DA_386TGate	EQU	  8Fh	; 386 陷阱门类型值


; DESCRIPTOR base, limit, attribute
; base dd
; limit dd, 使用低20位
; attribute dw, 高位字节的低4位总是为0，因为这4位被段限制字段占用
%macro DESCRIPTOR 3
    dw %2 & 0ffffh ; 填充低16位，段限制1
    dw %1 & 0ffffh ; 段基址1，16位
    db (%1 >> 16) & 0ffh ; 段基址2，8位
    dw ((%2 >> 8) & 0ff00h) | (%3 & 0f0ffh) ; 段限制2 + 加属性
    db (%1 >> 24) & 0ffh ; 高8位，基址3
%endmacro

; 声明一个选择子
%macro DECLARE_SELECTOR 2
    %1 equ %2-LABEL_GDT
%endmacro
